services:
  db:
    image: postgres:16
    container_name: nest_pg_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
